config/routes.rb
Icare::Application.routes.draw do
  devise_for :users

  resources :posts

  match '/geo_search', :to=>'geo_search#search'
  match '/search', :to => 'posts#search'
  root :to => "posts#index"

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :post

  has_attached_file :image,
                    :styles =>{
                        :thumb => '100x100>',
                        :medium => '300x300>',
                        :large => '600x600>'
                    },
                    :storage => :s3,
                    :bucket => 'media.smartbee.heroku.com',

                    #:path => "photos/:id/:filename",
                    :s3_credentials => {
                        :access_key_id => ENV['S3_KEY'],
                        :secret_access_key => ENV['S3_SECRET']
                    }
end

app/models/post.rb
require 'sunspot_rails'

class Post < ActiveRecord::Base
  validates :title, :presence => true


  acts_as_gmappable :validation => false

  acts_as_mappable :default_units => :miles,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :latitude,
                   :lng_column_name => :longitude

  has_many :assets, :dependent => :destroy
  accepts_nested_attributes_for :assets

  searchable do
    text :title, :content, :location
  end

  before_save :extract_city

  def gmaps4rails_address
    location
  end

  def gmaps4rails_infowindow
    if self.assets && self.assets.first && self.assets.first.image
      picture = self.assets.first.image.url(:thumb)
    end
    "#{title} <br> <p> <img src='#{picture}'> </p>"
  end

  #def gmaps4rails_marker_picture
  #  if self.assets && self.assets.first && self.assets.first.image
  #    picture = self.assets.first.image.url(:thumb)
  #  end
  #  {
  #      "picture" => picture, # string, mandatory
  #      "width" => "25", # string, mandatory
  #      "height" => "25" # string, mandatory
  #  }
  #end

  private

  def extract_city
    self.city ||= GeoKit::Geocoders::GoogleGeocoder.geocode(location).city
  rescue

  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/geo_search_controller.rb
require 'geokit'
class GeoSearchController < ApplicationController
  def search
    @title = "Search"

    origin = params[:origin]
    within = params[:within]

    if (!origin.empty? && !within.empty?)
      @json = Post.within(within, :origin=>origin).to_gmaps4rails
    else
      @json = Post.within(0, :origin=>"origin").to_gmaps4rails
    end

    #render(:template=>'posts/index')
    respond_to do |format|
      format.html
      format.js
    end

  end

end

app/controllers/posts_controller.rb
require 'geokit'
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show, :search]

  def search
    @search = Post.search do
      fulltext params[:search]
    end
    @posts = @search.results

    render 'index'
  end

  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.paginate(:page => params[:page]).all(:order=>"created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new
    4.times {@post.assets.build}

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def create
    @upload = Upload.new(params[:upload])
    if @upload.save
      render :json => {:pic_path => @upload.picture.url.to_s, :name => @upload.picture.instance.attributes["picture_file_name"]}, :content_type => 'text/html'
    else
      render :json => {:result => 'error'}, :content_type => 'text/html'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    if @title.nil?
      return "iCare"
    else
      return "#{@title} | iCare"
    end
  end

  def truncate_wrap_link full_txt, href, truncate_len, line_len
    truncated_text = truncate(full_txt, :length=>truncate_len, :omission=>"...")
    wrapped_text = word_wrap(truncated_text, :line_with=>line_len)
    link_to wrapped_text, href
  end

  def truncate_wrap_text full_txt, truncate_len, line_len
    truncated_text = truncate(full_txt, :length=>truncate_len, :omission=>"...")
    wrapped_text = word_wrap(truncated_text, :line_with=>line_len)
    return wrapped_text
  end

end

app/helpers/posts_helper.rb
module PostsHelper
  def price(param)
     if param.nil?
       return "TBD"
     else
       return "$#{param.to_i}"
     end
  end
end

app/views/geo_search/search.html.erb
<% form_tag :geo_search, :method=>':get', :remote=>true do %>
    <div class="field filter_field">
      With in <%= text_field_tag :within %> miles from <%= text_field_tag :origin %>
    </div>
    <div class="actions">
       <%= submit_tag "Search" %>
    </div>
<% end %>

<%= gmaps4rails(@json) %>

app/views/geo_search/search.js.erb
Gmaps.map.markers_conf.offset = 0;
Gmaps.map.replaceMarkers(<%=raw @json%>);

app/views/layouts/_header.html.erb
<%= link_to "iCare", root_path, :class => "brand" %>
<% form_tag search_path, :method => :get, :class => "pull-right" do %>
    <%= text_field_tag :search, params[:search], :placeholder => "Search", :class => "input-small" %>
    <%= submit_tag "Search", :name => nil, :class => "btn primary" %>
<% end %>
<nav>
  <ul class="nav">
    <% if user_signed_in? %>
        <li>
          <%= "#{current_user.email}" %>
        </li>
    <% end %>
    <li><%= link_to("Home", root_path) %></li>

    <% if user_signed_in? %>
        <li>
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
        </li>
    <% else %>
        <li>
          <%= link_to("Sign up", new_user_registration_path) %>
        </li>
        <li>
          <%= link_to("Sign in", new_user_session_path) %>
        </li>
    <% end %>

    <li><%= link_to("Help", "#") %></li>
  </ul>
</nav>

app/views/layouts/_photogallery.html.erb
<!-- gallery div start -->
<div class="gallery">

  <% if !@photo_gallery.nil? %>
      <% @photo_gallery.each do |pg| %>
          <div class=pg.css_class>
            <% logo = image_tag("rails.png", :alt => "Photo Gallery") %>
            <%= link_to logo, root_path %>
          </div>
      <% end %>
  <% end %>

</div>
<!-- gallery div end -->

<!-- clear both div -->
<div class="clear">&nbsp;</div>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag :all %>
<%= javascript_include_tag "application.js" %>
<%= javascript_include_tag "jquery-1.6.4.js" %>
<%= javascript_include_tag "jquery_ujs.js" %>
<%= javascript_include_tag "rails.js" %>
<%= javascript_include_tag "bootstrap-twipsy.js" %>
<%= javascript_include_tag "help_button.js" %>
<%= javascript_include_tag "utilities_bar.js" %>
<%= csrf_meta_tag %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= yield :head %>
  <%= yield :scripts %>
  <%= render 'layouts/stylesheets' %>

</head>

<body style="background-color: #eee">
<!-- html5 -->
<header>
  <div class="topbar">
    <div class="fill">
      <div class="container">
        <%= render 'layouts/header' %>
      </div>
    </div>
  </div>

</header>

<section>
  <div class="container">
    <div class="content">
      <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
      <% end %>
      <div class="row">
        <div class="span9">
          <%= yield %>
        </div>
        <div class="span5"></div>

      </div>
    </div>
    <footer>
        <p>&copy; Company 2011</p>

      </footer>
  </div>


</section>


</body>
</html>

app/views/partials/_geo_filter.html.erb
<% form_tag :geo_search, :method=>':get' do %>
    <div class="filter_field">
      <p>
        Within <%= text_field_tag :within, params[:within], :placeholder => "eg. 10", :class => "input-small line-height:normal" %>
        miles
        from <%= text_field_tag :origin, params[:origin], :placeholder => "eg. 95131", :class => "span3" %>
        <button class="btn success help_btn" data-original-title="Please input a distance based on a valid zip code or address. eg. Within '10' miles within '2386 Trade Zone Blvd, San Jose, CA'">?</button>
        <!--<a rel="twipsy" href="#" data-original-title="Some title text" class="btn success help_btn">?</a>-->
      </p>
      <br/>
      <%= submit_tag "Search", :class => "btn primary" %>
    </div>
    <br class="clearboth"/>
<% end %>

app/views/partials/_gmap.html.erb
<%= gmaps4rails(@json) %>

app/views/posts/_form.html.erb
<%= form_for(@post, :html => {:multipart=>true}) do |f| %>
    <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %>
      <br/>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :content %>
      <br/>
      <%= f.text_area :content %>
    </div>
    <div class="field">
      <%= f.label :location %>
      <br/>
      <%= f.text_field :location %>
    </div>

    <div class="field">
      <%= f.label :price %>
      <br/>
      <%= f.text_field :price %>
    </div>

    <div class="field">
      <% f.fields_for :assets do |asset| %>
          <% if asset.object.new_record? %>
              <%= asset.file_field :image %>
              <br>
          <% end %>
      <% end %>

    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div id="view_swtich_bar">
  <ul>
    <li>
      <%= image_tag("thumnail.png") %>
    </li>
    <li>
      <%= image_tag("title_small.png") %>
    </li>
    <li>
      <%= image_tag("normal_down.png") %>
    </li>
  </ul>
</div>

<div class="filter_container clearboth">
  <%= render 'partials/geo_filter' %>
</div>

<div class="row">
  <% if !@posts.nil? %>
      <% @posts.each do |post| %>
          <div class="post_spliter">
            <br />
            <div class="post">
                <span class="post_price">
                      <%= price post.price.to_i %>
                    </span>

                    <span class="post_title">
                      <%= truncate_wrap_link post.title, post, 60, 35 %>
                    </span>

                    <span class="post_content clearboth">
                      <%= truncate_wrap_text post.content, 140, 35 %>
                    </span>
              <br>

              <!-- Photo thumbs -->
              <% post.assets.each do |asset| %>

                  <div class="post_thumb">
                    <%= image_tag asset.image(:thumb) %>
                  </div>

              <% end %>

              <br class="clearboth">

              <div class="post_meta">
                <%= time_ago_in_words(post.created_at) %> ago
              </div>

              <div class="post_meta">
                <%= post.city %>
              </div>

            </div>
            <br />
            <br />
          </div>
      <% end %>

  <% end %>
</div>

<br/>
<%= link_to 'New Post', new_post_path %>

<%= will_paginate %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <%= price @post.price.to_i %>
  <%= @post.title %>
</p>

<p class="post_content">
  <%= @post.content %>
</p>

<p >
  <%= @post.location %>
</p>
<br>

<% @post.assets.each do |asset| %>

    <div >
      <%= image_tag asset.image(:original), :class => "post_original" %>
    </div>

<% end %>

<br class="clear display_block">

<p>
  <br>
<%= link_to 'Edit', edit_post_path(@post), :class => "clear_both" %> |
<%= link_to 'Back', posts_path, :class => "clear_both" %>
</p>